export const products = [
  {
    category: 'suit',
    size: [42, 44, 46, 48],
    color: 'blue',
    price: 178,
    image: '/store/blue_hoodie.jpg',
    slug: 'blue_hoodie',
    rating: 4.8,
    countInStock: 28,
  },
  {
    category: 't-shirt',
    size: [42, 44, 46, 48, 50, 52],
    color: 'yellow',
    price: 69,
    image: '/store/yellow_t-shirt.jpg',
    slug: 'yellow_t-shirt',
    rating: 4.6,
    countInStock: 20,
  },
  {
    category: 'sweatshirt',
    size: [46, 48, 50, 52],
    color: 'gray',
    price: 89,
    image: '/store/gray_sweatshirt.jpg',
    slug: 'gray_sweatshirt',
    rating: 5,
    countInStock: 12,
  },
  {
    category: 'summer suit',
    size: [42, 44, 46],
    color: 'pink',
    price: 138,
    image: '/store/pink_summer_suit.jpg',
    slug: 'pink_summer_suit',
    rating: 5,
    countInStock: 40,
  },
  {
    category: 't-shirt',
    size: [42, 44, 46, 48, 50, 52],
    color: 'blue',
    price: 69,
    image: '/store/blue_t-shirt.jpg',
    slug: 'blue_t-shirt',
    rating: 4.7,
    countInStock: 33,
  },
  {
    category: 'suit',
    size: [42, 46, 48, 50, 52],
    color: 'white',
    price: 178,
    image: '/store/white_hoodie.jpg',
    slug: 'white_hoodie',
    rating: 5,
    countInStock: 29,
  },
  {
    category: 'suit',
    size: [42, 46, 52],
    color: 'gray',
    price: 178,
    image: '/store/gray_hoodie.jpg',
    slug: 'gray_hoodie',
    rating: 5,
    countInStock: 18,
  },
  {
    category: 'summer suit',
    size: [42, 44, 46],
    color: 'yellow',
    price: 138,
    image: '/store/yellow_summer_suit.jpg',
    slug: 'yellow_summer_suit',
    rating: 5,
    countInStock: 11,
  },
  {
    category: 'palazzo',
    size: [42, 44, 50, 52],
    color: 'black',
    price: 148,
    image: '/store/black_palazzo.jpg',
    slug: 'black_palazzo',
    rating: 5,
    countInStock: 7,
  },
  {
    category: 'palazzo',
    size: [42, 50],
    color: 'brown',
    price: 148,
    image: '/store/brown_palazzo.jpg',
    slug: 'brown_palazzo',
    rating: 5,
    countInStock: 19,
  },
  {
    category: 'suit',
    size: [42, 44, 48, 52],
    color: 'brown',
    price: 178,
    image: '/store/brown_hoodie.jpg',
    slug: 'brown_hoodie',
    rating: 4,
    countInStock: 25,
  },

  // new items
  {
    category: 'suit',
    size: [42, 44, 52],
    color: 'bordeaux',
    price: 178,
    image: '/store/bordeaux-suit.jpg',
    slug: 'bordeaux-suit',
    rating: 4.6,
    countInStock: 23,
  },
  {
    category: 'suit',
    size: [42, 44, 52],
    color: 'beige',
    price: 155,
    image: '/store/beige-suit.jpg',
    slug: 'beige-suit',
    rating: 4.9,
    countInStock: 34,
  },
  {
    category: 'suit',
    size: [42, 44, 48],
    color: 'purple',
    price: 186,
    image: '/store/purple-suit.jpg',
    slug: 'purple-suit',
    rating: 4.4,
    countInStock: 13,
  },
  {
    category: 'suit',
    size: [42, 44, 48],
    color: 'yellow',
    price: 140,
    image: '/store/yellow-suit.jpg',
    slug: 'yellow-suit',
    rating: 3.5,
    countInStock: 13,
  },
  {
    category: 'suit',
    size: [44, 48],
    color: 'light-yellow',
    price: 186,
    image: '/store/light-yellow-suit.jpg',
    slug: 'light-yellow-suit',
    rating: 4.1,
    countInStock: 6,
  },
  {
    category: 'summer-suit',
    size: [42, 44, 46, 48],
    color: 'white',
    price: 188,
    image: '/store/white-summer-suit.jpg',
    slug: 'white-summer-suit',
    rating: 5,
    countInStock: 18,
  },
  {
    category: 'suit',
    size: [42, 44, 46, 48],
    color: 'dark-blue',
    price: 184,
    image: '/store/dark-blue-suit.jpg',
    slug: 'dark-blue-suit',
    rating: 4.9,
    countInStock: 15,
  },
  {
    category: 'suit',
    size: [42, 44, 46, 48],
    color: 'orange',
    price: 190,
    image: '/store/orange-suit.jpg',
    slug: 'orange-suit',
    rating: 4.9,
    countInStock: 15,
  },
];
